title: 黒帳キャラクター集
description: 黒帳のキャラクターと世界観をまとめたサイト
lang: ja
url: "https://kurotoba-fun.github.io"
baseurl: "/mainworld"
markdown: kramdown
permalink: pretty

collections:
  characters:
    output: true
    permalink: /characters/:name/
  academy_characters:
    output: true
    permalink: /academy/characters/:name/

defaults:
  - scope:
      path: ""
      type: "characters"
    values:
      layout: character
      list_path: /characters/
      theme: mainworld

  - scope:
      path: ""
      type: "academy_characters"
    values:
      layout: character
      list_path: /academy/characters/
      theme: academy
      
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
